# Generated by Django 4.1.7 on 2023-04-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_enq_message_enq_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enq',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staf',
            name='add',
        ),
        migrations.AddField(
            model_name='enq',
            name='message',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
