# Generated by Django 4.1.7 on 2023-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_enq_password_remove_staf_add_enq_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf',
            name='message',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
