# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_enq_message_enq_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
