# Generated by Django 4.1.7 on 2023-04-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staf',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staf',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staf',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
