# Generated by Django 4.1.7 on 2023-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_jew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
