# Generated by Django 4.1.7 on 2023-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_jew_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jew',
            name='gram',
            field=models.IntegerField(max_length=50),
        ),
    ]
