# Generated by Django 4.1.7 on 2023-04-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_cus'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('orid', models.CharField(max_length=200, null=True)),
                ('orn', models.CharField(max_length=200, null=True)),
                ('add', models.CharField(max_length=200, null=True)),
                ('pin', models.CharField(max_length=200, null=True)),
                ('pay', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
