# Generated by Django 4.1.7 on 2023-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_jew_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jew',
            name='mod',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
