# Generated by Django 4.1.7 on 2023-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_jew_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jew',
            name='mod',
            field=models.CharField(choices=[('ring', 'RING'), ('chain', 'CHAIN')], default='CHAIN', max_length=6),
        ),
    ]
